name: Install dependencies
description: Install npm dependencies and cache

inputs:
  path:
    description: Install path
    default: src
    type: string
  cache-key:
    description: Cache key
    type: string

runs:
  using: "composite"
  # working-directory: ${{ inputs.path }}
  steps:
    - id: try-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ${{ inputs.path }}/node_modules
        key: ${{ inputs.cache-key }}
    - run: npm ci
      if: ${{ !steps.try-cache.outputs.cache-hit }}
      shell: bash
      working-directory: ${{ inputs.path }}
# working-directory: ${{}}

# jobs:
#   install-deps:
#     name: Install dependencies
#     runs-on: ubuntu-latest
#     steps:
#       - id: try-cache
#         uses: actions/cache@v2
#         with:
#           path: |
#             ~/.npm
#             **/node_modules
#           key: ${{ inputs.cache-key }}
#       - run: npm ci
#         if: ${{ steps.try-cache.outputs.cache-hit }}
#         # working-directory: ${{ inputs.path }}