name: Install dependencies
description: Install npm dependencies and cache

inputs:
  path:
    description: Install path
    default: src
    type: string
  cache-key:
    description: Cache key
    type: string

runs:
  using: "composite"
  steps:
    - id: try-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ${{ inputs.path }}/node_modules
        key: ${{ inputs.cache-key }}
    - run: npm ci
      if: ${{ !steps.try-cache.outputs.cache-hit }}
      shell: bash
      working-directory: ${{ inputs.path }}