service: orm-layer
# app and org for use with dashboard.serverless.com
app: tally-backend
org: aroger7

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

layers:
  orm:
    path: nodejs
    name: ${self:provider.stage}-orm-layer
    compatibleRuntimes:
      - nodejs12.x