name: Deploy env
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'layers/orm-layer/**'
  workflow_dispatch:
env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - run: echo ::set-output name=env::${{ env.BRANCH_NAME }}
  deploy:
    needs: [get-env]
    uses: aroger7/tali-common/.github/workflows/orm-layer.yml@main
    with:
     env: ${{ needs.get-env.outputs.env }}