name: Deploy layers
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'layers/**'
  workflow_dispatch:
env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
jobs:
  deploy:
    name: Deploy ORM layer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: layers/orm-layer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: nelonoel/branch-name@v1.0.1
      - run: npm ci
        working-directory: layers/orm-layer/nodejs
      - run: npx serverless deploy --stage ${{ env.BRANCH_NAME }}
